from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel


class FlareLogEntry(BaseModel):
    """
    One log entry as stored in the Redis Stream and returned by the REST API.

    The 'id' field is the Redis Stream entry ID (auto-generated by XADD),
    e.g. "1708800000000-0". It is millisecond-precise and time-ordered.
    """

    id: str
    timestamp: datetime
    level: Literal["ERROR", "WARNING"]
    event: str
    message: str
    request_id: Optional[str] = None
    endpoint: Optional[str] = None
    http_method: Optional[str] = None
    http_status: Optional[int] = None
    ip_address: Optional[str] = None
    duration_ms: Optional[int] = None
    error: Optional[str] = None
    stack_trace: Optional[str] = None
    context: Optional[dict] = None
    request_body: Optional[Any] = None

    model_config = {"from_attributes": True}


class FlareLogPage(BaseModel):
    """Paginated response returned by GET /flare/api/logs."""

    logs: list[FlareLogEntry]
    total: int
    page: int
    limit: int
    pages: int


class FlareEndpointMetric(BaseModel):
    """Per-endpoint request metrics aggregated in memory by FlareMetrics."""

    endpoint: str
    count: int
    errors: int
    avg_latency_ms: int
    p95_latency_ms: int = 0
    max_latency_ms: int
    error_rate: float


class FlareMetricsSnapshot(BaseModel):
    """Snapshot of all endpoint metrics returned by GET /flare/api/metrics."""

    endpoints: list[FlareEndpointMetric]
    total_requests: int
    total_errors: int
    at_capacity: bool = False
    max_endpoints: int = 500


class FlareStats(BaseModel):
    """Summary statistics returned by GET /flare/api/stats."""

    total_entries: int
    errors_last_24h: int
    warnings_last_24h: int
    queue_length: int
    stream_length: int
    oldest_entry_ts: Optional[datetime] = None
    newest_entry_ts: Optional[datetime] = None


class FlareStorageActionResult(BaseModel):
    """Response returned by storage maintenance endpoints (trim, clear)."""

    ok: bool
    action: str
    detail: str = ""


class FlareHealthReport(BaseModel):
    """Health report returned by GET /flare/health."""

    status: Literal["ok", "degraded", "down"]
    storage_backend: str
    storage: Literal["ok", "error"]
    storage_error: Optional[str] = None
    worker_running: bool
    worker_flush_cycles: int
    queue_size: int
