from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel


class FlareLogEntry(BaseModel):
    """
    One log entry as stored in the Redis Stream and returned by the REST API.

    The 'id' field is the Redis Stream entry ID (auto-generated by XADD),
    e.g. "1708800000000-0". It is millisecond-precise and time-ordered.
    """

    id: str
    timestamp: datetime
    level: Literal["ERROR", "WARNING"]
    event: str
    message: str
    request_id: Optional[str] = None
    endpoint: Optional[str] = None
    http_method: Optional[str] = None
    http_status: Optional[int] = None
    ip_address: Optional[str] = None
    duration_ms: Optional[int] = None
    error: Optional[str] = None
    stack_trace: Optional[str] = None
    context: Optional[dict] = None

    model_config = {"from_attributes": True}


class FlareLogPage(BaseModel):
    """Paginated response returned by GET /flare/api/logs."""

    logs: list[FlareLogEntry]
    total: int
    page: int
    limit: int
    pages: int


class FlareStats(BaseModel):
    """Summary statistics returned by GET /flare/api/stats."""

    total_entries: int
    errors_last_24h: int
    warnings_last_24h: int
    queue_length: int
    stream_length: int
    oldest_entry_ts: Optional[datetime] = None
    newest_entry_ts: Optional[datetime] = None
